---
- name: Postgresql Install
  hosts: Linux-Postgres
  sudo: yes 
  tasks:
 
  - name: Install Postgresql Server!
    yum: name=postgresql-server state=latest
  - name: Initialize Database
    command: postgresql-setup initdb
    notify:
    - restart postgresql
  - name: ensure postgresql is running (and enable it at boot)
    service: name=postgresql.service state=started enabled=yes
  handlers:
    - name: restart postgresql
      service: name=postgresql.service state=restarted
